apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql-ns
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: postgresql
      version: '15.5.*'
      sourceRef:
        kind: OCIRepository
        name: bitnami-postgresql
      interval: 5m
  install:
    createNamespace: true
  releaseName: postgresql-release
