apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql-ns
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: postgresql-repository
    namespace: flux-system
  install:
    createNamespace: true
  releaseName: postgresql-release
