apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  interval: 10m0s
  timeout: 5m0s
  chartRef:
    kind: OCIRepository
    name: postgresql-repository
    namespace: flux-system
  install:
    createNamespace: true
  releaseName: postgresql-release
