apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  targetNamespace: postgresql-ns
  values:
    global:
      postgresql:
        auth:
          existingSecret: "postgresql-secret"
          secretKeys:
            adminPasswordKey: "adminPassword"
            userPasswordKey: "userPassword"            
