apiVersion: kustomize.config.k8s.io/v1beta1
namespace: postgresql-ns
kind: Kustomization
resources:
  - ../../../base
  - secrets.yaml
patches:
  - path: helm-release-patch.yaml
    target:
      kind: HelmRelease
