apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql2-ns
spec:
  values:
    resources:
      requests:
        cpu: "2"
        memory: 512Mi
      limits:
        cpu: "3"
        memory: 1024Mi
