---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kubeseal
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: '>=1.15.0-0'
  install:
    crds: Skip
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: kubeseal
  upgrade:
    crds: Skip
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: kubeseal
spec:
  interval: 1h0m0s
  url: https://bitnami-labs.github.io/sealed-secrets
