apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: postgresql-repository
  namespace: flux-system
spec:
  interval: 10m0s
  provider: generic
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    tag: "15.5.37"
