apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgresql-repository
  namespace: flux-system
spec:
  interval: 4h
  provider: generic
  url: https://registry-1.docker.io/bitnamicharts/postgresql
