apiVersion: helmrepositories.source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-postgresql
  namespace: flux-system
spec:
  interval: 4h
  provider: generic
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: "*"
